"""add info_synced_at to lastfm_artists

Revision ID: d5b929ae1174
Revises: 0762875a2f29
Create Date: 2026-07-10 19:46:48.621887

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5b929ae1174"
down_revision: str | Sequence[str] | None = "0762875a2f29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lastfm_artists", sa.Column("info_synced_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lastfm_artists", "info_synced_at")
    # ### end Alembic commands ###
