"""add info_synced_at to lastfm_artists

Revision ID: dca22ef5e6e3
Revises: 01343f3d13b3
Create Date: 2026-07-10 18:02:53.637893

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dca22ef5e6e3"
down_revision: str | Sequence[str] | None = "01343f3d13b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lastfm_artists", sa.Column("info_synced_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lastfm_artists", "info_synced_at")
    # ### end Alembic commands ###
